version: "3.9"
services:
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/fake_db_populate.sql:/docker-entrypoint-initdb.d/fake_db_populate.sql
