models:
  - name: category
    type: TreeClassifier
    data_source:
      type: db
      name: category
      url: db
      port: 5432
      database: mydb
      user: postgres
      password: postgres
      query:
        features: SELECT name, location FROM category
        target: SELECT category FROM category
